# Generated by Django 4.2.5 on 2023-09-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='body',
            old_name='votes',
            new_name='upvotes',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='title_note',
            new_name='note_title',
        ),
    ]
